---
# file: dev.yml

# Configuration for the Hub address resolver
hubResolver:
  type: simple
  hubs:
    datawire:
      - 127.0.0.1:52689

# Configuration for the JSON Web Token validator
jsonWebToken:

  # The path to the keystore file
  keyStorePath: src/test/resources/fixtures/test_hs256-2.jceks

  # The type of keystore
  keyStoreType: jceks

  # The password protecting the keystore
  keyStorePassword: notasecret