sudo: false

language: java
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - python-pip

install:
  - pip install --user datawire-quark

script:
  - ./gradlew :hub-client:compileQuark build test
