sudo: false
language: java
jdk:
- oraclejdk8

env:
  global:
    - AWS_ACCESS_KEY: AKIAJQBKCFCK2YIEEUGQ
    - secure: "elAN8GhVn9SCIQZtZR8mkiCeiIddgXuFr+3X059lO3SolDPVftruXdhbmTERZaceAIDFNCz4Yhe0NEpByesy3oLHDjBNtZmdQAoSTxELQHQDgQVEZo5BparkxhrJ8vEcSVbWzBCYCEQVqIb262ABmiRex6/Tsy2RG+amZ3V0FkxaKbriNRTPxJJOyzwfexzmjwwhQ1WSVgCwfOJonxooenFuAovRuiyu1WV7+8CbR+rU06negHDufcqsvwMWxJ92v3OWqJjhL8DDeO+LpBx9IpeyvpstmXlpp3k5DjWUeG4G1ZLCTMJvTJDAjYjyONLrQ9daY7S4tUbroWEhyF9wD8QR8VVN+uKXLCGCzun/NPW3rI8mg1TxSrQQFoAdK2zEUgpuRkQ+yUGo+2f9AaD/TmlcbRDo1gbkh+P+cXCQNbRRvZ8UG4e57+5AqVi8LjyzKA6JLctgvzldumfnRQaWecoIZySSqs4wvcQtyBLOg6+ZeNc/JfD1sN5ixEUJiW8FL4ActDJmEWJ+TySReZ4aHVXUw5OfmETec/Q80P+uZe6tH/sE19YO5Z0kfdeES0JrhDz7OFxo/l89t5BIxIIMUirvHbqZaUbtQxwB5j92hCA8iUUD+NDQ3hHafWm5QYK74qKZHC+SMGpNcFlmqyIXeDJXFBYG4tSVAhTwXVZZ1co="

addons:
  apt:
    packages:
    - python-pip
    - uuid

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

install:
- scripts/tci_bootstrap.sh

script:
- scripts/tci_build.sh
- PATH=$(pwd)/build/bin:$PATH scripts/packer.sh
