---
tenant: datawire

#
# "serviceRegistry" - REQUIRED
#
# Configuration for the Hub services registry.
#
serviceRegistry:
  type: simple
  open: true
  port: 52689
  bindHost: 127.0.0.1

jwt:
  type: jceks
  path: ../etc/example-HS256.jceks
  password: notasecret