---
# file: dev.yml

gateway:
  type: simple
  bindAddress: 127.0.0.1
  port: 8080
  jsonWebToken:
    keyStorePath: "../demo-ks-256.jceks"
    keyStoreType: jceks
    keyStorePassword: notasecret

#discoveryResolver:
#  type: ec2-instance
#  region: us-east-1

discoveryResolver:
  type: simple
  servers:
    H3KA9BVWH1:
      - 127.0.0.1:52689